" -I./public_headers/usr/lib/gcc/x86_64-linux-gnu/9/include/include"
" -I./public_headers/usr/include/c++/9"
" -I./public_headers/usr/include/x86_64-linux-gnu/c++/9"
" -I./public_headers/usr/include/c++/9/backward"
" -I./public_headers/usr/lib/gcc/x86_64-linux-gnu/9/include"
" -I./public_headers/usr/local/include"
" -I./public_headers/usr/include/x86_64-linux-gnu"
" -I./public_headers/usr/include"